/*
 * TIMER1_Cfg.h
 *
 *  Created on: Jun 27, 2023
 *      Author: hassan
 */

#ifndef INCLUDE_MCAL_TIMER1_TIMER1_CFG_H_
#define INCLUDE_MCAL_TIMER1_TIMER1_CFG_H_

//servo motor from 499 2999

#define WGM_CHOICE TIMER1_NORMAL
#define COM1A_CHOICE TIMER1_NORMAL_DIO
#define COM1B_CHOICE TIMER1_NORMAL_DIO
#define CLK_CHOICE TIMER1_CLK_8
#define ICR1_VALUE 0
#define OCR1A_VALUE 0
#define OCR1B_VALUE 0
#define INPUT_CAPTURE_INTERRUPT_ENABLE TIMER1_ENABLE
#define OUTPUT_COMPARE_A_MATCH_INTERRUPT_ENABLE TIMER1_DISABLE
#define OUTPUT_COMPARE_B_MATCH_INTERRUPT_ENABLE TIMER1_DISABLE
#define OVERFLOW_INTERRUPT_ENABLE TIMER1_DISABLE

#endif /* INCLUDE_MCAL_TIMER1_TIMER1_CFG_H_ */
